# R matrix
> R Matrix Tutorial: Create, Print, add Column, Slice

The notebook is based on [this tutorial](https://www.guru99.com/r-matrix-tutorial.html)
A matrix is a 2-dimensional array that has m number of rows and n number of columns. In other words, matrix is a combination of two or more vectors with the same data type.

## Create Matrix in R
We can create a matrix with the function matrix(). This function takes three arguments:

```R
matrix(data, nrow, ncol, byrow = FALSE)
```
Arguments: 

* data: The collection of elements that R will arrange into the rows and columns of the matrix \
* nrow: Number of rows 
* ncol: Number of columns 
* byrow: The rows are filled from the left to the right. We use `byrow = FALSE` (default values), if we want the matrix to be filled by the columns i.e. the values are filled top to bottom.

Let's construct two 5x2 matrix with a sequence of number from 1 to 10, one with byrow = TRUE and one with byrow = FALSE to see the difference.

In [1]:
# Construct a matrix with 5 rows that contain the numbers 1 up to 10 and byrow =  TRUE 
matrix_a <- matrix(c(1:10),byrow=TRUE, nrow=5)
matrix_a

[,1] [,2]
[1,] 1     2  
[2,] 3     4  
[3,] 5     6  
[4,] 7     8  
[5,] 9    10

In [2]:
# Print dimension of the matrix with dim()

dim(matrix_a) # 5 rows by 2 columns

[1] 5 2

In [5]:
matrix_c <- matrix(1:12, byrow = FALSE, ncol = 3)
matrix_c

[,1] [,2] [,3]
[1,] 1    5     9  
[2,] 2    6    10  
[3,] 3    7    11  
[4,] 4    8    12

In [6]:
dim(matrix_c)

[1] 4 3

## Bind column
```cbind()```

In [9]:
# concatenate c(2:6) to the matrix_c
matrix_a1<-cbind(matrix_c, c(2:5))
# check the dimension
dim(matrix_a1)

[1] 4 4

In [10]:
matrix_a1

[,1] [,2] [,3] [,4]
[1,] 1    5     9   2   
[2,] 2    6    10   3   
[3,] 3    7    11   4   
[4,] 4    8    12   5

In [11]:
matrix_d<-cbind(matrix_a1,matrix_c)
dim(matrix_d)

[1] 4 7

In [12]:
matrix_d

[,1] [,2] [,3] [,4] [,5] [,6] [,7]
[1,] 1    5     9   2    1    5     9  
[2,] 2    6    10   3    2    6    10  
[3,] 3    7    11   4    3    7    11  
[4,] 4    8    12   5    4    8    12

## Bind row
```rbind()```

In [13]:
matrix_e = rbind(c(2:8),matrix_d)
dim(matrix_e)

[1] 5 7

In [14]:
matrix_e

[,1] [,2] [,3] [,4] [,5] [,6] [,7]
[1,] 2    3     4   5    6    7     8  
[2,] 1    5     9   2    1    5     9  
[3,] 2    6    10   3    2    6    10  
[4,] 3    7    11   4    3    7    11  
[5,] 4    8    12   5    4    8    12

## Slice a matrix

We can select elements one or many elements from a matrix by using the square brackets ```[ ]```. This is where slicing comes into the picture.

For example:

* ```matrix_c[1,2]``` selects the element at the first row and second column.
* ```matrix_c[1:3,2:3] ```results in a matrix with the data on the rows 1, 2, 3 and columns 2, 3,
* ```matrix_c[,1]``` selects all elements of the first column.
* ```matrix_c[1,]``` selects all elements of the first row.

This part is exactly like [numpy indexing](https://docs.scipy.org/doc/numpy/reference/arrays.indexing.html), except:
* start and end point has to be a value, no ```[:2]```
* everything starts from 1 instead of 0
* the start point means >=, end point means <=

In [18]:
matrix_e[1:2,3:5]

[,1] [,2] [,3]
[1,] 4    5    6   
[2,] 9    2    1

In [19]:
matrix_e[,2:5]

[,1] [,2] [,3] [,4]
[1,] 3     4   5    6   
[2,] 5     9   2    1   
[3,] 6    10   3    2   
[4,] 7    11   4    3   
[5,] 8    12   5    4